local telescope = require("telescope")
local telescope_builtin = require("telescope.builtin")

vim.keymap.set("n", "<leader>ff", function() telescope_builtin.find_files() end)
vim.keymap.set("n", "<leader>fw", function() telescope_builtin.grep_string() end)
vim.keymap.set("n", "<leader>fg", function() telescope_builtin.live_grep() end)
vim.keymap.set("n", "<leader>fb", function() telescope_builtin.buffers() end)
vim.keymap.set("n", "<leader>fh", function() telescope_builtin.help_tags() end)
vim.keymap.set("n", "<leader>t", function() telescope.extensions.file_browser.file_browser() end)

vim.keymap.set("n", "<c-]>", vim.lsp.buf.definition)
vim.keymap.set("n", "K", vim.lsp.buf.hover)
vim.keymap.set("n", "gD", vim.lsp.buf.implementation)
vim.keymap.set("n", "<c-k>", vim.lsp.buf.signature_help)
vim.keymap.set("n", "1gD", vim.lsp.buf.type_definition)
vim.keymap.set("n", "gr", vim.lsp.buf.references)
vim.keymap.set("n", "g0", vim.lsp.buf.document_symbol)
vim.keymap.set("n", "gW", vim.lsp.buf.workspace_symbol)
vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "ga", vim.lsp.buf.code_action)
