[packages.arch]
explicit = [
  "archlinux-wallpaper",
  "aws-cli-v2",
  "base-devel",
  "bat",
  "bitwarden-cli",
  "bottom",
  "dust",
  "fd",
  "fluxcd",
  "fzf",
  "git",
  "git-delta",
  "github-cli",
  "gnupg",
  "helm",
  "jq",
  "kitty",
  "kubectl",
  "lazygit",
  "lsd",
  "luarocks",
  "neovim",
  "python",
  "ranger",
  "restic",
  "ripgrep",
  "rustup",
  "rye",
  "starship",
  "ttf-firacode-nerd",
  "yq",
  "zsh",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-syntax-highlighting",
]
deps = ["python-neovim", "wl-clipboard", "xsel"]

[packages.darwin]
brews = [
   "awscli",
   "bat",
   "bitwarden-cli",
   "bottom",
   "chezmoi",
   "dust",
   "fd",
   "fluxcd/tap/flux",
   "gh",
   "git",
   "git-delta",
   "gnupg",
   "helm",
   "jq",
   "kubectl",
   "lazygit",
   "lsd",
   "luarocks",
   "neovim",
   "ranger",
   "ripgrep",
   "rustup",
   "rye",
   "starship",
   "yq",
   "zsh",
   "zsh-autosuggestions",
   "zsh-completions",
   "zsh-syntax-highlighting",
]
casks = [
   "font-fira-code-nerd-font",
   "wezterm",
]
