"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[kubernetes]
disabled = false

[memory_usage]
disabled = false

[status]
disabled = false

[sudo]
disabled = false

[time]
disabled = true
